openapi: 3.0.1
info:
  title: monster-dryad
  x-cortex-tag: monster-dryad
  x-cortex-custom-metadata:
    alignment: lawful-good
    type: construct
    challenge_rating: 25
    legendary: false
    armor_class: 22
    hit_points: 269
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-dryad
      alias: github-token-test
